### ISSUE TITLE
Is the setup missing info?

### ISSUE THREAD

**Issue by akrabdev** [Dhyeythumar/video-streamer#2]
Followed the steps ,  and after
 `train = subprocess.run(["mlagents-learn", "config.yaml", "--run-id=train-1", "--env=ML-Agents-with-Google-Colab/headless_build/3DBall_example/3dball.x86_64", "--base-port=" + str(randrange(9000, 9999))], cwd="/content/", stdout=subprocess.PIPE) ` is executed all I get is black screen on twitch : 
![image](https://user-images.githubusercontent.com/37980706/117862598-1e1bb100-b293-11eb-8c4b-3a2d2df31a81.png)

Logs example : 
![image](https://user-images.githubusercontent.com/37980706/117865335-288b7a00-b296-11eb-808f-7ad80b59ac86.png)

**Comment by dhyeythumar** [comment]
Hi @abdallahakrab, I think you are using the environment provided in [ML Agents with Google Colab](https://github.com/Dhyeythumar/ML-Agents-with-Google-Colab) repo. So this env is headless/server build & this won't work.

**You need the Unity Build files without headless/server build**. [headless/server build doesn't have any interface so you won't get any output to twitch]

**Comment by akrabdev** [comment]
Thank you .. I had wrong understanding of headless build .
Solved
